# Generated by Django 5.0 on 2023-12-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="time_create",
            field=models.DateField(auto_now_add=True),
        ),
    ]
